# Generated by Django 3.2.8 on 2021-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
